from __future__ import annotations

import re
import secrets
from datetime import datetime, timezone
from io import BytesIO
from pathlib import Path

from PIL import Image, UnidentifiedImageError
from PIL.Image import DecompressionBombError

from cartometa.atomic_write import write_json_atomic
# Imported rather than duplicated: the form's valid values and the inference
# cannot drift apart if there is only one owner of the list.
from cartometa.extract.categories import CATEGORIES
from cartometa.models import DIFFICULTIES, ORIGIN_MANUAL, TIER_MANUAL, MetaRecord
from cartometa.review.store import CountryPaths, load_metas, read_json_list

# A pasted screenshot rarely goes beyond a megabyte. The cap does not exist to
# constrain usage but so that a misbehaving client cannot fill the disk.
MAX_IMAGE_BYTES = 8 * 1024 * 1024

EXTENSION_BY_FORMAT = {"PNG": ".png", "JPEG": ".jpg", "WEBP": ".webp", "GIF": ".gif"}

# Exact shapes of the identifiers an image may attach to: hand-entered metas
# (`man-` + 4 hex) and imported tagged metas (`tag-` + 6 hex, cf.
# cartometa.tagged.importer.proposal_id). Plonk It ids (4 bare chars) stay
# refused: their metas.json is regenerated by cartometa-extract, which would
# silently drop the reference.
_ATTACHABLE_ID = re.compile(r"^(man-[0-9a-f]{4}|tag-[0-9a-f]{6})$")


class ManualMetaError(ValueError):
    """Manual entry refused: missing field, or unusable image."""


def new_meta_id(existing: set[str]) -> str:
    """A free `man-xxxx` identifier.

    The prefix makes any collision with Plonk It identifiers impossible, as those
    are four characters with no prefix.
    """
    while True:
        candidate = f"man-{secrets.token_hex(2)}"
        if candidate not in existing:
            return candidate


def _required(value: str | None, label: str) -> str:
    cleaned = (value or "").strip()
    if not cleaned:
        raise ManualMetaError(f"{label} is required")
    return cleaned


def _editorial_fields(
    *,
    title: str | None,
    description: str | None,
    category: str | None,
    source_url: str | None,
    difficulty: str | None,
) -> dict:
    """The fields a human owns on a meta, validated.

    Shared by creation and edition rather than duplicated: the two must accept
    exactly the same values, and the form behind them is the same one.
    """
    validated = {
        "title": _required(title, "the title"),
        "description": _required(description, "the description"),
    }
    if category not in CATEGORIES:
        raise ManualMetaError(
            f"unknown category: {category!r} (expected {', '.join(CATEGORIES)})"
        )
    # Empty is legitimate and means "not rated": only a *filled* value has to be one
    # of the known levels.
    if difficulty and difficulty not in DIFFICULTIES:
        raise ManualMetaError(
            f"unknown difficulty: {difficulty!r} (expected {', '.join(DIFFICULTIES)})"
        )
    validated["category"] = category
    validated["source_url"] = (source_url or "").strip()
    validated["difficulty"] = difficulty or None
    return validated


def _apply_difficulty(meta: dict, difficulty: str | None) -> None:
    """Set the level, or remove the key altogether.

    "Not rated" is the *absence* of the field, never an empty string: that is what
    the build reads, and a meta carrying `""` would publish the same thing while
    reading, in the file, as a judgement someone had made.
    """
    if difficulty:
        meta["difficulty"] = difficulty
    else:
        meta.pop("difficulty", None)


def create_meta(
    paths: CountryPaths,
    *,
    title: str | None,
    description: str | None,
    category: str | None,
    source_url: str | None = "",
    difficulty: str | None = None,
) -> dict:
    """Create a hand-entered meta and append it to the country's manual file."""
    champs = _editorial_fields(
        title=title, description=description, category=category,
        source_url=source_url, difficulty=difficulty,
    )
    meta = MetaRecord(
        # Uniqueness is judged over BOTH sources: an identifier free on the manual
        # side but already taken on the imported side would break the merge.
        id=new_meta_id({m["id"] for m in load_metas(paths)}),
        country=paths.country,
        tier=TIER_MANUAL,
        title=champs["title"],
        description=champs["description"],
        category=champs["category"],
        source_url=champs["source_url"],
        extracted_at=datetime.now(timezone.utc).isoformat(),
        description_origin="manual",
        origin=ORIGIN_MANUAL,
    ).to_dict()
    # Not a `MetaRecord` field: an unrated meta must carry no key at all, where the
    # dataclass would always serialise a `difficulty: null`.
    _apply_difficulty(meta, champs["difficulty"])

    existing = read_json_list(paths.manual_metas)
    existing.append(meta)
    write_json_atomic(paths.manual_metas, existing)
    return meta


def update_meta(
    paths: CountryPaths,
    meta_id: str,
    *,
    title: str | None,
    description: str | None,
    category: str | None,
    source_url: str | None = "",
    difficulty: str | None = None,
) -> dict:
    """Rewrite the editorial fields of a hand-entered meta, and return it.

    Only the metas of `data/manual/<CC>/metas.json` can be edited. The other sources
    — Plonk It, RMRG, tagged imports — live under `data/metas/`, which is gitignored
    and rewritten wholesale by `cartometa-extract` / `cartometa-import-tagged`: an
    edit there would look saved, then disappear at the next import. The same reason
    keeps Plonk It identifiers out of `save_image`.

    Everything is validated before the file is read, so a refused edit writes nothing.
    """
    champs = _editorial_fields(
        title=title, description=description, category=category,
        source_url=source_url, difficulty=difficulty,
    )
    metas = read_json_list(paths.manual_metas)
    target = next((m for m in metas if m["id"] == meta_id), None)
    if target is None:
        raise _refuse_edit(paths, meta_id)

    difficulte = champs.pop("difficulty")
    target.update(champs)
    _apply_difficulty(target, difficulte)
    write_json_atomic(paths.manual_metas, metas)
    return target


def _refuse_edit(paths: CountryPaths, meta_id: str) -> ManualMetaError:
    """Why this meta cannot be edited — two very different fixes.

    A meta absent from `data/manual/` but known to another source is a scope
    limitation to be explained; an identifier known to nobody is a mistake.
    """
    if any(m["id"] == meta_id for m in load_metas(paths)):
        return ManualMetaError(
            f"{meta_id!r} is not in data/manual/{paths.country}/metas.json: its texts "
            "come from a regenerable source, which the next import would rewrite. "
            "Only hand-entered metas can be edited."
        )
    return ManualMetaError(f"unknown meta: {meta_id!r}")


def _relative_to_cwd(path: Path) -> str:
    """Path as the server serves it: relative to the project root.

    The server serves files from its working directory, and imported metas already
    store `input/…` there. We keep the same convention so the interface has only one
    rule: prefix with `/`.
    """
    root = Path.cwd().resolve()
    absolute = (root / path).resolve()
    if absolute.is_relative_to(root):
        return absolute.relative_to(root).as_posix()
    return absolute.as_posix()


def save_image(paths: CountryPaths, meta_id: str, raw: bytes) -> str:
    """Write a manual meta's image and attach it to that meta."""
    # Validated before any path is built and before the lookup in metas.json: the
    # safety rail must not depend on the file's content, only on the shape of the
    # identifier itself.
    if Path(meta_id).name != meta_id or not _ATTACHABLE_ID.fullmatch(meta_id):
        raise ManualMetaError(f"invalid meta identifier: {meta_id!r}")
    if len(raw) > MAX_IMAGE_BYTES:
        raise ManualMetaError(
            f"image too large: {len(raw)} bytes, maximum {MAX_IMAGE_BYTES}"
        )
    try:
        image = Image.open(BytesIO(raw))
        image_format = image.format
        image.verify()
    except (UnidentifiedImageError, OSError, ValueError):
        raise ManualMetaError("the bytes received do not form a readable image") from None
    except DecompressionBombError:
        raise ManualMetaError("the image declares dimensions too large to be processed") from None
    extension = EXTENSION_BY_FORMAT.get(image_format or "")
    if extension is None:
        raise ManualMetaError(f"image format not accepted: {image_format!r}")

    # The meta may live in the hand-entered file or in the tagged-imports one:
    # update whichever holds it. The image bytes always land in manual_images —
    # versioned — because a screenshot is irreplaceable, unlike the tagged
    # texts which any re-import regenerates.
    for source in (paths.manual_metas, paths.tagged_metas):
        metas = read_json_list(source)
        target = next((m for m in metas if m["id"] == meta_id), None)
        if target is None:
            continue
        # The file name comes from the identifier received, but that identifier
        # has already been validated against the attachable shapes (`man-` + 4
        # hex or `tag-` + 6 hex, no path component) then found in metas.json:
        # so no client-supplied path component can reach the file system.
        paths.manual_images.mkdir(parents=True, exist_ok=True)
        destination = paths.manual_images / f"{meta_id}{extension}"
        destination.write_bytes(raw)
        target["image"] = _relative_to_cwd(destination)
        write_json_atomic(source, metas)
        return target["image"]
    raise ManualMetaError(f"unknown meta: {meta_id!r}")
